### ISSUE TITLE
about airdrop

### ISSUE THREAD

**Issue by qdtjgk** [zksync/credo#5] opened 2023-06-24 03:28 UTC
I think users who use and build projects uninterruptedly for a long time should be rewarded

**Comment by sioodmy** [comment] 2023-06-24 11:58
Duplicate of #2

**Comment by asgharsata1** [comment] 2023-06-24 13:06
> I think users who use and build projects uninterruptedly for a long time should be rewarded

yes

**Comment by kyawsamuilove** [comment] 2023-06-25 11:28
But don't think too much bro))

**Closed** 2023-08-10 23:37 UTC

**Comment by asgharsata1** [comment] 2023-08-11 20:11
Anyway, I hope we will all be well rewarded for our efforts
